import type { Spell } from "./spells";

export const DEFAULT_SPELLS: Spell[] = [
  // Cantrips (Common to many classes)
  {
    id: "fireBolt",
    name: "Raio de Fogo",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você emite um raio de fogo na direção de uma criatura ou objeto à sua escolha dentro do alcance. Faça um ataque de magia à distância. Se atingir, o alvo sofre 1d10 de dano de fogo.",
    prepared: true,
    classes: ["wizard", "sorcerer", "warlock"]
  },
  {
    id: "light",
    name: "Luz",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, M (uma vela ou fósforo)",
    duration: "1 hora (concentração)",
    description: "Você toca um objeto e ele brilha com luz. O objeto emite luz brilhante em um raio de 20 pés e luz fraca por mais 20 pés.",
    prepared: true,
    classes: ["wizard", "sorcerer", "bard", "cleric", "druid"]
  },
  {
    id: "mageHand",
    name: "Mão Mágica",
    level: 0,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "1 minuto",
    description: "Você cria um espectro de mão flutuante e fantasmagórico em um ponto desocupado à sua escolha dentro do alcance. A mão dura pelo tempo da magia ou até você dispensá-la como uma ação.",
    prepared: false,
    classes: ["wizard", "sorcerer", "warlock", "bard"]
  },
  {
    id: "prestidigitation",
    name: "Prestidigitação",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "10 pés",
    components: "V, S",
    duration: "1 hora",
    description: "Você cria um dos seguintes efeitos mágicos dentro do alcance: cria uma fumastra inofensiva, acende ou apaga uma pequena chama, limpa ou suja um objeto, esquenta, esfria ou tempera comida.",
    prepared: false,
    classes: ["wizard", "sorcerer", "warlock", "bard"]
  },
  {
    id: "guidance",
    name: "Orientação",
    level: 0,
    school: "Divinação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Você toca uma criatura disposta. Quando a criatura fizer uma rolagem de teste de habilidade ou salvaguarda antes da magia terminar, ela pode rolar um d4 e adicionar o resultado à rolagem.",
    prepared: true,
    classes: ["cleric", "druid"]
  },
  {
    id: "tollTheDead",
    name: "Recear os Mortos",
    level: 0,
    school: "Necromancia",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você toca o sino que só os mortos podem ouvir. Uma criatura à sua escolha dentro do alcance deve fazer uma salvaguarda de Sabedoria. Se o alvo estiver com pontos de vida ausentes, sofre 1d12 de dano necrótico. Caso contrário, sofre 1d8 de dano necrótico.",
    prepared: true,
    classes: ["cleric", "warlock"]
  },
  {
    id: "sacredFlame",
    name: "Chama Sagrada",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Chama radiante desce do céu em um ponto à sua escolha dentro do alcance. Cada criatura em uma esfera de 5 pés de raio centrada nesse ponto deve fazer uma salvaguarda de Destreza. Uma criatura sofre 1d6 de dano radiante em uma falha, ou metade do dano em um sucesso.",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "druidcraft",
    name: "Artifício de Druida",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você prevê o tempo ou cria um pequeno efeito meteorológico. Você também pode fazer com que flores brotem, criar uma leve brisa ou fazer um som de animal.",
    prepared: true,
    classes: ["druid"]
  },
  {
    id: "shillelagh",
    name: "Shillelagh",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação bônus",
    range: "Toque",
    components: "V, S, M (folhas de carvalho)",
    duration: "1 minuto",
    description: "O madeiro de uma clava ou cajado que você segura é imbuido com energia. A arma se torna mágica e usa seu modificador de habilidade para ataques e danos.",
    prepared: true,
    classes: ["druid"]
  },
  {
    id: "thornWhip",
    name: "Chicote de Espinhos",
    level: 0,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S, M (um espinho de planta)",
    duration: "Instantânea",
    description: "Você cria um chicote comprido e espinhoso que arrasta uma criatura. Faça um ataque de magia. Se atingir, o alvo sofre 1d6 de dano de perfuração e é puxado 10 pés para mais perto de você.",
    prepared: true,
    classes: ["druid"]
  },
  {
    id: "viciousMockery",
    name: "Zombaria Vil",
    level: 0,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você unleashes uma string de insults laced com arcane energy. Uma criatura à sua escolha dentro do alcance deve fazer uma salvaguarda de Sabedoria. Se falhar, sofre 1d4 de dano psíquico e tem desvantagem no próximo ataque.",
    prepared: true,
    classes: ["bard"]
  },
  {
    id: "minorIllusion",
    name: "Ilusão Menor",
    level: 0,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "1 minuto",
    description: "Você cria um som ou imagem de objeto dentro do alcance. A imagem não tem som, smell, texture ou temperatura.",
    prepared: true,
    classes: ["wizard", "bard", "sorcerer", "warlock"]
  },
  {
    id: "rayOfFrost",
    name: "Raio de Gelo",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você emite um raio de gelo na direção de uma criatura ou objeto à sua escolha dentro do alcance. Faça um ataque de magia à distância. Se atingir, o alvo sofre 1d8 de dano de gelo e sua velocidade é reduzida em 10 pés até o próximo turno.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "shockingGrasp",
    name: "Agarrar Elétrico",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    description: "Você cria energia elétrica em suas mãos. Faça um ataque de magia corpo a corpo. Se atingir, o alvo sofre 1d8 de dano de relâmpago e não pode tomar reações até o próximo turno.",
    prepared: true,
    classes: ["sorcerer", "warlock", "wizard"]
  },
  {
    id: "trueStrike",
    name: "Golpe Verdadeiro",
    level: 0,
    school: "Divinação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Concentração, até 1 rodada",
    description: "Você ganha uma breve visão do futuro. Da próxima vez que você atacar uma criatura antes da magia terminar, você tem vantagem na rolagem de ataque.",
    prepared: false,
    classes: ["bard", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "chillTouch",
    name: "Toque Gélido",
    level: 0,
    school: "Necromancia",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você cria um feixe de energia gélida. Faça um ataque de magia à distância. Se atingir, o alvo sofre 1d8 de dano necrótico e não pode recuperar pontos de vida até o próximo turno.",
    prepared: true,
    classes: ["sorcerer", "warlock", "wizard"]
  },
  {
    id: "mending",
    name: "Consertar",
    level: 0,
    school: "Transmutação",
    castingTime: "1 minuto",
    range: "Toque",
    components: "V, S, M (duas agulhas de couro)",
    duration: "Instantânea",
    description: "Você toca um objeto quebrado e o conserta. A magia pode consertar uma única break ou tear em um objeto.",
    prepared: true,
    classes: ["wizard", "artificer", "bard"]
  },
  {
    id: "message",
    name: "Mensagem",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (um pequeno pedaço de cobre)",
    duration: "1 rodada",
    description: "Você pode enviar uma mensagem telepática para uma criatura que você possa ver. A criatura pode responder telepaticamente.",
    prepared: true,
    classes: ["bard", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "bladeWard",
    name: "Proteger Lâmina",
    level: 0,
    school: "Abjuração",
    castingTime: "1 reação",
    range: "Pessoal",
    components: "V, S",
    duration: "1 rodada",
    description: "Você estende sua mão e rastros de energia azul protegem você. Você tem resistência a dano contundante, perfurante e cortante de ataques de arma não mágicos.",
    prepared: true,
    classes: ["warlock", "wizard"]
  },
  {
    id: "dancingLights",
    name: "Luzes Dançantes",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (um pouco de fósforo ou uma vela)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria até quatro torch-sized lights que aparecem onde você escolher dentro do alcance. Você pode mover os lights como uma ação bônus.",
    prepared: true,
    classes: ["bard", "sorcerer", "wizard"]
  },
  {
    id: "poisonSpray",
    name: "Spray Venenoso",
    level: 0,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "10 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você expele spray de poison em uma criatura. Faça um ataque de magia corpo a corpo. Se atingir, o alvo deve fazer uma salvaguarda de Constituição ou sofre 1d12 de dano de veneno.",
    prepared: true,
    classes: ["druid", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "resistance",
    name: "Resistência",
    level: 0,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (um pequeno manto de seda)",
    duration: "Concentração, até 1 minuto",
    description: "Você toca uma criatura disposta. Ela pode rolar um d4 e adicionar o resultado a uma salvaguarda de sua escolha.",
    prepared: true,
    classes: ["cleric", "druid"]
  },
  {
    id: "shapeWater",
    name: "Modelar Água",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Instantânea ou Concentração, até 1 hora",
    description: "Você escolhe uma área de água que você possa ver dentro do alcance. Você pode freeze, boil, ou modelar a água como uma ação.",
    prepared: true,
    classes: ["druid", "sorcerer", "wizard"]
  },
  {
    id: "thaumaturgy",
    name: "Taumaturgia",
    level: 0,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você manifesta um efeito mágico menor. Você pode criar um efeito sensorial instantâneo, como uma faísca, som ou odor, ou causar uma pequena mudança ambiental.",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "stabilize",
    name: "Estabilizar",
    level: 0,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você estabiliza uma criatura com 0 pontos de vida. Se a criatura não tiver mortos, ela para de morrer e pode fazer rolagens de morte com vantagem.",
    prepared: true,
    classes: ["cleric"]
  },

  // Level 1 Spells
  {
    id: "magicMissile",
    name: "Míssil Mágico",
    level: 1,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você cria três mísseis brilhantes de energia. Cada míssil atinge uma criatura que você possa ver à sua escolha dentro do alcance, causando 1d4+1 de dano de força.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "shield",
    name: "Escudo",
    level: 1,
    school: "Abjuração",
    castingTime: "1 reação",
    range: "Pessoal",
    components: "V, S",
    duration: "1 minuto",
    description: "Uma barreira invisível de força mágica aparece e protege você. Até o final da magia, você tem um bônus de +5 na CA e é imune a mísseis mágicos.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "detectMagic",
    name: "Detectar Magia",
    level: 1,
    school: "Divinação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 30 pés)",
    components: "V, S",
    duration: "Concentração, até 10 minutos",
    description: "Pela duração, você sente a presença de magia dentro de 30 pés de você. Se você sentir magia, pode usar sua ação para ver uma aura fraca ao redor de qualquer criatura ou objeto visível que carrega magia.",
    prepared: false,
    classes: ["wizard", "cleric", "druid", "paladin", "ranger", "bard", "sorcerer"]
  },
  {
    id: "burningHands",
    name: "Mãos Ardentes",
    level: 1,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 15 pés)",
    components: "V, S",
    duration: "Instantânea",
    description: "Você mantém as mãos com os polegares se tocando e estende os dedos. Uma fina cortina de chamas irrompe de suas mãos. Cada criatura em uma área de 15 pés de cone deve fazer uma salvaguarda de Destreza. Uma criatura sofre 3d6 de dano de fogo em uma falha, ou metade do dano em um sucesso.",
    prepared: false,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "cureWounds",
    name: "Curar Ferimentos",
    level: 1,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    description: "Uma criatura que você tocar reganha 1d8 + seu modificador de habilidade de conjuração de pontos de vida.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "ranger", "bard"]
  },
  {
    id: "healingWord",
    name: "Palavra Curativa",
    level: 1,
    school: "Evocação",
    castingTime: "1 ação bônus",
    range: "60 pés",
    components: "V",
    duration: "Instantânea",
    description: "Uma criatura à sua escolha dentro do alcance reganha 1d4 + seu modificador de habilidade de conjuração de pontos de vida.",
    prepared: true,
    classes: ["cleric", "druid", "bard"]
  },
  {
    id: "bless",
    name: "Bênção",
    level: 1,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S, M (um pouco de água benta)",
    duration: "Concentração, até 1 minuto",
    description: "Você abençoa até três criaturas à sua escolha dentro do alcance. Cada criatura ganha um d4 para adicionar às rolagens de ataque e salvaguardas.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "guidingBolt",
    name: "Projétil Guiador",
    level: 1,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "1 rodada",
    description: "Um flash de luz irrompe do seu ponto. Uma criatura à sua escolha dentro do alcance deve fazer uma salvaguarda de Destreza. Se falhar, sofre 4d6 de dano radiante e o próximo ataque contra ela tem vantagem.",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "inflictWounds",
    name: "Infligir Ferimentos",
    level: 1,
    school: "Necromancia",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Instantânea",
    description: "Faça um ataque de magia corpo a corpo. Se atingir, o alvo sofre 3d10 de dano necrótico.",
    prepared: false,
    classes: ["cleric"]
  },
  {
    id: "sanctuary",
    name: "Santuário",
    level: 1,
    school: "Abjuração",
    castingTime: "1 ação bônus",
    range: "30 pés",
    components: "V, S, M (um pequeno espelho de prata)",
    duration: "1 minuto",
    description: "Você protege uma criatura contra ataques. Até a magia terminar, a primeira vez que a criatura for atacada, o atacante deve fazer uma salvaguarda de Sabedoria.",
    prepared: false,
    classes: ["cleric"]
  },
  {
    id: "charmPerson",
    name: "Encantar Pessoa",
    level: 1,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "1 hora",
    description: "Você tenta encantar um humanoid. Ele deve fazer uma salvaguarda de Sabedoria. Se falhar, é charmed por você e o considera um amigo conhecido.",
    prepared: false,
    classes: ["bard", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "heroism",
    name: "Heroísmo",
    level: 1,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Uma criatura disposta que você tocar ganha pontos de vida temporários e é imune a medo.",
    prepared: true,
    classes: ["bard", "paladin"]
  },
  {
    id: "huntersMark",
    name: "Marca do Caçador",
    level: 1,
    school: "Divinação",
    castingTime: "1 ação bônus",
    range: "90 pés",
    components: "V, S",
    duration: "Concentração, até 1 hora",
    description: "Você escolhe uma criatura que você possa ver dentro do alcance e mystical a marca. Você tem vantagem em testos de Percepção e Survival para encontrar a criatura, e causa 1d6 de dano extra quando a ataca.",
    prepared: true,
    classes: ["ranger", "paladin"]
  },
  {
    id: "entangle",
    name: "Enredar",
    level: 1,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "90 pés",
    components: "V, S, M (sementes de qualquer planta)",
    duration: "Concentração, até 1 minuto",
    description: "Plantas gramíneas e ervas em uma área de 20 pés de raio se tornam grudentas e difíceis. Cada criatura na área deve fazer uma salvaguarda de Força ou fica restrita.",
    prepared: true,
    classes: ["druid", "ranger"]
  },
  {
    id: "fogCloud",
    name: "Névoa",
    level: 1,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Concentração, até 1 hora",
    description: "Você cria uma esfera de névoa pesada com raio de 20 pés. A área é heavily obscured.",
    prepared: true,
    classes: ["druid", "ranger", "wizard", "sorcerer"]
  },
  {
    id: "goodberry",
    name: "Baga Boa",
    level: 1,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma baga)",
    duration: "Instantânea",
    description: "Você cria até 10 bagas mágicas. Cada baga restaura 1 ponto de vida quando comida.",
    prepared: true,
    classes: ["druid", "ranger"]
  },
  {
    id: "jump",
    name: "Saltar",
    level: 1,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma perna de rã)",
    duration: "1 minuto",
    description: "Você toca uma criatura. Seu salto em distância é triplicado até a magia terminar.",
    prepared: true,
    classes: ["druid", "ranger", "sorcerer", "wizard"]
  },
  {
    id: "animalFriendship",
    name: "Amizade Animal",
    level: 1,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S, M (um pouco de comida)",
    duration: "24 horas",
    description: "Um animal beast que você possa ver dentro do alcance deve fazer uma salvaguarda de Sabedoria. Se falhar, o animal considera você um amigo.",
    prepared: true,
    classes: ["druid", "ranger"]
  },

  // Level 2 Spells
  {
    id: "scorchingRay",
    name: "Raio Abrasador",
    level: 2,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você cria três raios de fogo. Cada raio atinge uma criatura ou objeto que você possa ver dentro do alcance. Cada raio causa 6d6 de dano de fogo.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "mistyStep",
    name: "Passo Nebuloso",
    level: 2,
    school: "Conjuração",
    castingTime: "1 ação bônus",
    range: "30 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você se teletransporta até 30 pés para um espaço desocupado que você possa ver.",
    prepared: true,
    classes: ["wizard", "sorcerer", "warlock", "bard", "cleric", "druid"]
  },
  {
    id: "invisibility",
    name: "Invisibilidade",
    level: 2,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma pálpebra envolvida em goma arábica)",
    duration: "Concentração, até 1 hora",
    description: "Uma criatura que você tocar se torna invisível. Se o alvo estiver carregando equipamento, isso também se torna invisível.",
    prepared: false,
    classes: ["wizard", "sorcerer", "bard", "warlock"]
  },
  {
    id: "spiritualWeapon",
    name: "Arma Espiritual",
    level: 2,
    school: "Evocação",
    castingTime: "1 ação bônus",
    range: "60 pés",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Você cria uma arma spectral flutuante. Como uma ação bônus, você pode fazer a arma atacar uma criatura a 5 pés dela, causando 1d8 + seu modificador de habilidade de dano de força.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "aid",
    name: "Ajuda",
    level: 2,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S, M (um pequeno pano de seda)",
    duration: "8 horas",
    description: "Até três criaturas à sua escolha ganham 5 pontos de vida temporários e seu máximo de pontos de vida aumenta em 5.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "prayerOfHealing",
    name: "Oração Cura",
    level: 2,
    school: "Evocação",
    castingTime: "10 minutos",
    range: "30 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você evoca healing energy que pode restore up to six creatures. Cada criatura reganha 2d8 + seu modificador de pontos de vida.",
    prepared: true,
    classes: ["cleric", "druid"]
  },
  {
    id: "holdPerson",
    name: "Prender Pessoa",
    level: 2,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (uma pequena corda reta)",
    duration: "Concentração, até 1 minuto",
    description: "Você escolha um humanoid que você possa ver dentro do alcance. Ele deve fazer uma salvaguarda de Sabedoria. Se falhar, está paralizado.",
    prepared: true,
    classes: ["cleric", "warlock", "wizard", "sorcerer", "bard"]
  },
  {
    id: "silence",
    name: "Silêncio",
    level: 2,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Concentração, até 10 minutos",
    description: "Para a duração, não há som em uma esfera de 20 pés de raio centrada em um ponto à sua escolha dentro do alcance.",
    prepared: true,
    classes: ["cleric", "bard", "ranger"]
  },
  {
    id: "darkness",
    name: "Escuridão",
    level: 2,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, M (pêlo de morcego com gota de piche)",
    duration: "Concentração, até 10 minutos",
    description: "Você cria uma esfera de escuridão mágica com raio de 15 pés. A esfera se move com você e está heavily obscured.",
    prepared: true,
    classes: ["warlock", "sorcerer", "wizard"]
  },
  {
    id: "spiderClimb",
    name: "Escalada de Aranha",
    level: 2,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma gota de betume e uma aranha)",
    duration: "Concentração, até 1 hora",
    description: "Uma criatura que você tocar ganha a habilidade de escalar superfícies verticais, mesmo de cabeça para baixo.",
    prepared: true,
    classes: ["druid", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "web",
    name: "Teia",
    level: 2,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (um pouco de teia de aranha)",
    duration: "Concentração, até 1 hora",
    description: "Você cria uma área de teias em um ponto à sua escolha. A área é difficult terrain e qualquer criatura que comece seu turno na área deve fazer uma salvaguarda de Força ou fica restrita.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "cloudOfDaggers",
    name: "Nuvem de Adagas",
    level: 2,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (uma agulha de bordar)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria uma nuvem de adagas flutuantes em um ponto à sua escolha. Qualquer criatura que comece seu turno na nuvem sofre 4d4 de dano de perfuração.",
    prepared: true,
    classes: ["wizard", "sorcerer", "warlock", "bard"]
  },
  {
    id: "enhanceAbility",
    name: "Aumentar Habilidade",
    level: 2,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (pêlo ou cabelo de uma besta)",
    duration: "Concentração, até 1 hora",
    description: "Você toca uma criatura e escolhe uma habilidade. A criatura ganha vantagem em testes dessa habilidade.",
    prepared: true,
    classes: ["druid", "bard", "sorcerer", "wizard"]
  },
  {
    id: "moonbeam",
    name: "Feixe de Lua",
    level: 2,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (sementes de moonflower)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria um feixe de luz lunar. Cada criatura no feixe deve fazer uma salvaguarda de Constituição ou sofre 2d10 de dano radiante.",
    prepared: true,
    classes: ["druid"]
  },
  {
    id: "sleetStorm",
    name: "Tempestade de Granizo",
    level: 2,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "150 pés",
    components: "V, S, M (um pouco de pó ou terra)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria uma tempestade de granizo em um cilindro de 40 pés de altura e 10 pés de raio. A área é heavily obscured e difficult terrain.",
    prepared: true,
    classes: ["druid", "wizard", "sorcerer"]
  },

  // Level 3 Spells
  {
    id: "fireball",
    name: "Bola de Fogo",
    level: 3,
    school: "Evocação",
    castingTime: "1 ação",
    range: "150 pés (30 cubos)",
    components: "V, S, M (um pequeno bola de enxofre e fósforo)",
    duration: "Instantânea",
    description: "Uma explosão brilhante irrompe do seu ponto. Cada criatura em uma esfera de 20 pés de raio centrada nesse ponto deve fazer uma salvaguarda de Destreza. Uma criatura sofre 8d6 de dano de fogo em uma falha, ou metade do dano em um sucesso.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "fly",
    name: "Voar",
    level: 3,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma pena de qualquer pássaro)",
    duration: "Concentração, até 10 minutos",
    description: "Você toca uma criatura disposta. O alvo ganha um velocidade de voo de 60 pés. Quando a magia termina, o alvo cai se ainda estiver no ar.",
    prepared: false,
    classes: ["wizard", "sorcerer", "warlock"]
  },
  {
    id: "lightningBolt",
    name: "Relâmpago",
    level: 3,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 100 pés)",
    components: "V, S, M (um pouco de pele de seda e âmbar)",
    duration: "Instantânea",
    description: "Você libera um raio de relâmpago em uma linha de 100 pés de comprimento e 5 pés de largura. Cada criatura na linha deve fazer uma salvaguarda de Destreza. Uma criatura sofre 8d6 de dano de relâmpago em uma falha, ou metade do dano em um sucesso.",
    prepared: false,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "dispelMagic",
    name: "Dissipar Magia",
    level: 3,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Escolha uma criatura, objeto ou efeito mágico. Você faz uma rolagem de habilidade de conjuração contra o CD 10 + o nível da magia. Se sucesso, a magia termina.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "ranger", "bard", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "revivify",
    name: "Reviver",
    level: 3,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (diamantes no valor de 300 po)",
    duration: "Instantânea",
    description: "Você toca uma criatura que morreu nos últimos 10 minutos. Ela retorna à vida com 1 ponto de vida.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "spiritGuardians",
    name: "Guardiões Espirituais",
    level: 3,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 15 pés)",
    components: "V, S, M (um pequeno símbolo sagrado)",
    duration: "Concentração, até 10 minutos",
    description: "Você invoca espíritos flutuantes. Qualquer criatura hostil que entrar na área ou começar seu turno lá deve fazer uma salvaguarda de Sabedoria. Se falhar, sofre 3d8 de dano radiante (se bom) ou necrótico (se mau).",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "animateDead",
    name: "Animar Mortos",
    level: 3,
    school: "Necromancia",
    castingTime: "1 minuto",
    range: "10 pés",
    components: "V, S, M (uma gota de sangue, um pedaço de carne e pó de ossos)",
    duration: "Instantânea",
    description: "Você toca um corpo humanoide ou esqueleto. Ele se levanta como um zombie ou skeleton que obedece seus comandos.",
    prepared: false,
    classes: ["cleric", "warlock", "wizard"]
  },
  {
    id: "callLightning",
    name: "Chamar Relâmpago",
    level: 3,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S",
    duration: "Concentração, até 10 minutos",
    description: "Uma nuvem de tempestade aparece no ar. Como uma ação, você pode chamar um raio que causa 3d10 de dano de relâmpago.",
    prepared: true,
    classes: ["druid"]
  },
  {
    id: "conjureAnimals",
    name: "Conjurar Animais",
    level: 3,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (uma pequena bolsa de seda com comida)",
    duration: "Concentração, até 1 hora",
    description: "Você conjura feixes que se tornam animais. Você pode conjurar 2 beast de Challenge Rating 1/4 ou menos, 4 beast de CR 1/2 ou menos, ou 8 beast de CR 1/4 ou menos.",
    prepared: true,
    classes: ["druid", "ranger"]
  },
  {
    id: "sleetStorm",
    name: "Tempestade de Granizo",
    level: 3,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "300 pés",
    components: "V, S, M (pó e um pouco de água)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria uma tempestade de granizo em um cilindro de 40 pés de altura e 20 pés de raio. A área é heavily obscured e difficult terrain.",
    prepared: true,
    classes: ["druid", "wizard", "sorcerer"]
  },
  {
    id: "bestowCurse",
    name: "Conceder Maldição",
    level: 3,
    school: "Necromancia",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Você toca uma criatura e a amaldiçoa. Escolha um dos seguintes efeitos: desvantagem em testes de habilidade, desvantagem em ataques, ou perda de ação.",
    prepared: false,
    classes: ["cleric", "warlock", "wizard"]
  },
  {
    id: "fear",
    name: "Medo",
    level: 3,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "Cone de 30 pés",
    components: "V, S, M (uma pena de coruja branca)",
    duration: "Concentração, até 1 minuto",
    description: "Você projeta um fantasma de medo. Cada criatura em um cone deve fazer uma salvaguarda de Sabedoria. Se falhar, fica com medo de você.",
    prepared: true,
    classes: ["warlock", "wizard", "bard"]
  },
  {
    id: "haste",
    name: "Acelerar",
    level: 3,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S, M (uma folha de shamrock)",
    duration: "Concentração, até 1 minuto",
    description: "Uma criatura disposta que você tocar ganha ação adicional e velocidade dobrada. Quando a magia termina, a criatura sofre 1 nível de exaustão.",
    prepared: true,
    classes: ["sorcerer", "wizard"]
  },
  {
    id: "slow",
    name: "Lentidão",
    level: 3,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (uma gota de mel)",
    duration: "Concentração, até 1 minuto",
    description: "Você altera o tempo em torno de até seis criaturas. Cada criatura deve fazer uma salvaguarda de Sabedoria. Se falhar, sua velocidade é halved e só pode usar uma ação ou movimento.",
    prepared: true,
    classes: ["sorcerer", "wizard"]
  },
  {
    id: "stinkingCloud",
    name: "Nuvem Fétida",
    level: 3,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "90 pés",
    components: "V, S, M (um ovo podre e um pouco de alho)",
    duration: "Concentração, até 1 minuto",
    description: "Você cria uma esfera de gás amarelo e fétido. Qualquer criatura que termine seu turno na nuvem deve fazer uma salvaguarda de Constituição ou fica poisoned.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "tinyHut",
    name: "Cabana Pequena",
    level: 3,
    school: "Evocação",
    castingTime: "1 minuto",
    range: "30 pés",
    components: "V, S, M (uma pequena agulha de cristal)",
    duration: "8 horas",
    description: "Você cria uma cúpula de força que abriga até nove criaturas de tamanho médio ou menor. É resistente ao clima e impede entrada de criaturas.",
    prepared: true,
    classes: ["wizard", "bard"]
  },

  // Level 4 Spells
  {
    id: "fireShield",
    name: "Escudo de Fogo",
    level: 4,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 10 pés)",
    components: "V, S, M (um pouco de fósforo)",
    duration: "Concentração, até 1 minuto",
    description: "Finas chamas irrompem de você. Você tem resistência a dano de fogo, e quando uma criatura a 5 pés de você lhe atingir com um ataque corpo a corpo, ela sofre 2d10 de dano de fogo.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "greaterInvisibility",
    name: "Invisibilidade Maior",
    level: 4,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (uma pálpebra envolvida em goma arábica com pó de diamante)",
    duration: "Concentração, até 1 minuto",
    description: "Você ou uma criatura disposta que você tocar se torna invisível. A magia termina para um alvo que atacar ou lançar uma magia.",
    prepared: false,
    classes: ["wizard", "sorcerer", "bard"]
  },
  {
    id: "polymorph",
    name: "Polimorfar",
    level: 4,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (uma lagarta em âmbar)",
    duration: "Concentração, até 1 hora",
    description: "Você transforma uma criatura que você possa ver em uma beast com CR igual ou menor. A criatura assume os stats da beast.",
    prepared: true,
    classes: ["wizard", "sorcerer", "bard"]
  },
  {
    id: "stoneskin",
    name: "Pele de Pedra",
    level: 4,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (diamante no valor de 100 po)",
    duration: "Concentração, até 1 hora",
    description: "Você toca uma criatura disposta. Ela ganha resistência a dano contundante, perfurante e cortante não mágico.",
    prepared: true,
    classes: ["druid", "ranger", "sorcerer", "wizard"]
  },
  {
    id: "deathWard",
    name: "Proteção Contra Morte",
    level: 4,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (um pouco de prata em pó)",
    duration: "8 horas",
    description: "Você toca uma criatura e a protege contra morte. Se a criatura sofrer dano que a reduziria a 0 pontos de vida, ela cai para 1 ponto de vida em vez disso.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "guardianOfFaith",
    name: "Guardião da Fé",
    level: 4,
    school: "Evocação",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V",
    duration: "8 horas",
    description: "Você evoca um guardião celestial. Ele ocupa um espaço e ataca qualquer criatura hostil que entrar em seu alcance.",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "iceStorm",
    name: "Tempestade de Gelo",
    level: 4,
    school: "Evocação",
    castingTime: "1 ação",
    range: "300 pés",
    components: "V, S, M (um pouco de pó ou terra)",
    duration: "Instantânea",
    description: "Você cria uma tempestade de granizo e pedras. Cada criatura em um cilindro de 20 pés de raio sofre 2d8 de dano contundante e 4d6 de dano de gelo.",
    prepared: true,
    classes: ["druid", "sorcerer", "wizard"]
  },
  {
    id: "locateCreature",
    name: "Localizar Criatura",
    level: 4,
    school: "Divinação",
    castingTime: "1 ação",
    range: "Pessoal",
    components: "V, S, M (uma folha de carvalho)",
    duration: "Concentração, até 1 hora",
    description: "Você descreve ou nomeia uma criatura. Você sente a direção da criatura se ela estiver no mesmo plano.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "ranger", "bard", "wizard"]
  },
  {
    id: "banishment",
    name: "Banir",
    level: 4,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (um objeto que o alvo odeia)",
    duration: "Concentração, até 1 minuto",
    description: "Você tenta banir uma criatura. Se falhar em uma salvaguarda de Carisma, é banida para um plano demônio por 1 minuto.",
    prepared: true,
    classes: ["cleric", "paladin", "warlock", "wizard"]
  },
  {
    id: "blight",
    name: "Praga",
    level: 4,
    school: "Necromancia",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Você causa necromantic energy em uma criatura. Ela sofre 8d8 de dano necrótico. Plantas e plant creatures têm desvantagem na salvaguarda.",
    prepared: true,
    classes: ["druid", "warlock", "wizard"]
  },
  {
    id: "confusion",
    name: "Confusão",
    level: 4,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "90 pés",
    components: "V, S, M (três nozes)",
    duration: "Concentração, até 1 minuto",
    description: "Você causa confusão em criaturas. Cada criatura deve fazer uma salvaguarda de Sabedoria. Se falhar, fica confused e age aleatoriamente.",
    prepared: true,
    classes: ["bard", "druid", "sorcerer", "wizard"]
  },
  {
    id: "dimensionDoor",
    name: "Porta Dimensional",
    level: 4,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "500 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você se teletransporta até 500 pés para um espaço desocupado que você possa ver. Você pode levar uma criatura disposta.",
    prepared: true,
    classes: ["warlock", "wizard", "sorcerer", "bard"]
  },
  {
    id: "hallucinatoryTerrain",
    name: "Terreno Alucinatório",
    level: 4,
    school: "Ilusão",
    castingTime: "10 minutos",
    range: "300 pés",
    components: "V, S, M (uma pedra, um pouco de terra e um pouco de água)",
    duration: "24 horas",
    description: "Você cria uma ilusão de terreno natural. A ilusão parece real mas não tem substância.",
    prepared: true,
    classes: ["druid", "ranger", "wizard", "bard"]
  },

  // Level 5 Spells
  {
    id: "coneOfCold",
    name: "Cone de Gelo",
    level: 5,
    school: "Evocação",
    castingTime: "1 ação",
    range: "Pessoal (raio de 60 pés)",
    components: "V, S, M (um cristal ou agulha de metal)",
    duration: "Instantânea",
    description: "Uma explosão de ar frio irrompe de suas mãos. Cada criatura em um cone de 60 pés deve fazer uma salvaguarda de Constituição. Uma criatura sofre 12d8 de dano de gelo em uma falha, ou metade do dano em um sucesso.",
    prepared: true,
    classes: ["wizard", "sorcerer"]
  },
  {
    id: "teleport",
    name: "Teleporte",
    level: 5,
    school: "Conjuração",
    castingTime: "1 ação",
    range: "10 pés",
    components: "V",
    duration: "Instantânea",
    description: "Você se teletransporta junto com até 8 outras criaturas dispostas para um destino que você conheça. A viagem pode falhar dependendo de sua familiaridade com o destino.",
    prepared: false,
    classes: ["wizard", "sorcerer", "warlock", "bard"]
  },
  {
    id: "dominatePerson",
    name: "Dominar Pessoa",
    level: 5,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Você tenta dominar um humanoid. Se falhar em uma salvaguarda de Sabedoria, é charmed por você e deve obedecer seus comandos.",
    prepared: true,
    classes: ["bard", "warlock", "wizard", "sorcerer"]
  },
  {
    id: "scrying",
    name: "Advinhação",
    level: 5,
    school: "Divinação",
    castingTime: "10 minutos",
    range: "Pessoal",
    components: "V, S, M (uma bola de cristal no valor de 100 po)",
    duration: "Concentração, até 10 minutos",
    description: "Você pode observar uma criatura ou objeto à distância. Você vê e ouve como se estivesse lá.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "ranger", "bard", "sorcerer", "warlock", "wizard"]
  },
  {
    id: "raiseDead",
    name: "Reviver Morto",
    level: 5,
    school: "Necromancia",
    castingTime: "1 hora",
    range: "Toque",
    components: "V, S, M (diamantes no valor de 500 po)",
    duration: "Instantânea",
    description: "Você retorna uma criatura morta à vida. Ela retorna com 1 ponto de vida e pode sofrer uma penalidade permanente.",
    prepared: true,
    classes: ["cleric", "paladin"]
  },
  {
    id: "flameStrike",
    name: "Golpe de Chama",
    level: 5,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S, M (sementes de fogo)",
    duration: "Instantânea",
    description: "Uma coluna de fogo divino desce do céu. Cada criatura em um cilindro de 10 pés de raio sofre 4d8 de dano de fogo e 4d8 de dano radiante.",
    prepared: true,
    classes: ["cleric"]
  },
  {
    id: "massCureWounds",
    name: "Curar Ferimentos em Massa",
    level: 5,
    school: "Evocação",
    castingTime: "1 ação",
    range: "60 pés",
    components: "V, S",
    duration: "Instantânea",
    description: "Até seis criaturas à sua escolha dentro do alcance reganham 3d8 + seu modificador de pontos de vida.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "bard"]
  },
  {
    id: "greaterRestoration",
    name: "Restauração Maior",
    level: 5,
    school: "Abjuração",
    castingTime: "1 ação",
    range: "Toque",
    components: "V, S, M (pó de diamante no valor de 100 po)",
    duration: "Instantânea",
    description: "Você remove todos os efeitos de uma criatura, incluindo curses, diseases, poisons, blindness, deafness e reduction de habilidades.",
    prepared: true,
    classes: ["cleric", "druid", "paladin", "bard"]
  },
  {
    id: "planarBinding",
    name: "Vinculação Planar",
    level: 5,
    school: "Abjuração",
    castingTime: "1 hora",
    range: "60 pés",
    components: "V, S, M (um símbolo da autoridade da criatura)",
    duration: "24 horas",
    description: "Você tenta vincular uma celestial, elemental, fey ou fiend. Se falhar em uma salvaguarda de Carisma, deve servir você por 24 horas.",
    prepared: true,
    classes: ["warlock", "wizard"]
  },
  {
    id: "modifyMemory",
    name: "Modificar Memória",
    level: 5,
    school: "Encantamento",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Concentração, até 1 minuto",
    description: "Você tenta modificar memórias de uma criatura. Se falhar em uma salvaguarda de Sabedoria, você pode alterar, apagar ou implantar memórias.",
    prepared: true,
    classes: ["bard", "wizard"]
  },
  {
    id: "seeming",
    name: "Aparência",
    level: 5,
    school: "Ilusão",
    castingTime: "1 ação",
    range: "30 pés",
    components: "V, S",
    duration: "Concentração, até 8 horas",
    description: "Você altera a aparência física de criaturas. Cada criatura pode parecer qualquer humanoid de tamanho médio ou menor.",
    prepared: true,
    classes: ["bard", "sorcerer", "wizard"]
  },
  {
    id: "transmuteRock",
    name: "Transmutar Rocha",
    level: 5,
    school: "Transmutação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (argila e água)",
    duration: "Instantânea",
    description: "Você transforma rocha em lama ou lama em rocha. A área afetada é um cubo de 40 pés.",
    prepared: true,
    classes: ["druid", "wizard"]
  },
  {
    id: "wallOfForce",
    name: "Muro de Força",
    level: 5,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (pó de quartzo ou vidro moído)",
    duration: "Concentração, até 10 minutos",
    description: "Você cria uma parede invisível de força. A parede não pode ser danificada e bloqueia movimento e magias.",
    prepared: true,
    classes: ["wizard"]
  },
  {
    id: "wallOfStone",
    name: "Muro de Pedra",
    level: 5,
    school: "Evocação",
    castingTime: "1 ação",
    range: "120 pés",
    components: "V, S, M (uma pequena pedra)",
    duration: "Instantânea",
    description: "Você cria uma parede de pedra. A parede pode ter qualquer forma e tem 6 polegadas de espessura.",
    prepared: true,
    classes: ["druid", "wizard"]
  }
];

export const getSpellsByClass = (classKey: string, level: number): Spell[] => {
  return DEFAULT_SPELLS.filter(spell => 
    spell.classes?.includes(classKey) && 
    spell.level <= Math.min(level, 5)
  );
};

export const getCantripsByClass = (classKey: string): Spell[] => {
  return DEFAULT_SPELLS.filter(spell => 
    spell.level === 0 && 
    spell.classes?.includes(classKey)
  );
};

export const SPELL_SCHOOLS = {
  abjuration: "Abjuração",
  conjuration: "Conjuração", 
  divination: "Divinação",
  enchantment: "Encantamento",
  evocation: "Evocação",
  illusion: "Ilusão",
  necromancy: "Necromancia",
  transmutation: "Transmutação"
} as const;

export const getSpellsByLevel = (level: number): Spell[] => {
  return DEFAULT_SPELLS.filter(spell => spell.level === level);
};

export const getSpellsBySchool = (school: string): Spell[] => {
  return DEFAULT_SPELLS.filter(spell => spell.school === school);
};

export const getCantrips = (): Spell[] => {
  return DEFAULT_SPELLS.filter(spell => spell.level === 0);
};

export const getSpellById = (id: string): Spell | undefined => {
  return DEFAULT_SPELLS.find(spell => spell.id === id);
};
